{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "sonarr.fullname" . -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: sonarr-timeouts
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ $fullName }}
  timeout:
    http:
      requestTimeout: 0s
  connection:
    bufferLimit: 32Ki
{{- end }}

